travis:
  secure:
    BINSTAR_TOKEN: jLKhEqQGxWPoGJnIJR4/OHY/bkso5wg0acdXCrO9ezO51Ir7XFL6VEWycf8kuv0eT1HzXUWgsaGu1QLDZhk0btRCORBrazQwBUJJ5YvgXmfAIiGtH+Ryd67GEoROnHFWFWQw68yHeZhofHfTK2d/kPg0qds6CO2+YDbpKMcW/g/fZmC/GwScSAW4NDOLfLfFqml4Ef9J29hlSCHn5lx7PNxCbs2w2NYK26nQDB808EMfFGqJWgdqiOBHCiDMi5kx+IyY/EMHm9PpcONp6hBED3pQoOjGai7F7EW1HQa06d2LfH5ijX8yRdbWokpcA3bvp+S4Vy3pMHQtFZHnK0EbTOxjAGRSU2WgkheYhhZwoC54o314Txnp6cWQIz7S8J76TLRMQW9QZM2Z0MXmsLfkPAvDAzkVJG1YuzhSUJNdz2Oe4yRISmBMYOyTpZDia/dhiEdY6F5BvUo9R0z1i25vfKjOVGZjjm0fJ+QumhUOrbG1ehUkVa4sYPQ/SIHcSBnB9Z59komgfsdcLajQrFMjvwCdg/3zDKv0aWSEs+W84QNZ9HEiPY3IuT+RC3KOuGiFWhE8eog795J2OVMtPph8pQTsQQgDsCmz+Pl8fzopeVV87JaBmWx+y5FV22Qr4tSSo2S4jzmD/zTcvF1KK52eA7ij25DDwmp69YXfVcTCaHc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
